### PR TITLE
Updating theme, field templates to add label class to output (re: html behind individual fellowship pages is broken...)

### PR DESCRIPTION
**Pull request by retrospec**
i.e. request gwu-libraries/lai-drupal/issues/8

### CODE REVIEW

**Review by maxstarkenburg — CHANGES_REQUESTED** [review]
Thanks. Just saw this now since I use my personal e-mail address for GitHub.

Anyway, let's look at coordinating Sass output formats so that we have fewer noisy diffs, since my generation of the CSS will apparently result in a different output style.

Also, more germane to the substance of this ticket, the comments I put in the .scss files about the selectors being fragile can probably now be removed.

**Comment by maxstarkenburg** [comment]
While I think the apparent Dart vs. Ruby Sass output differences (`0.5em` vs. `.5em`, etc.) might create some noise next time I make a styling change in this repo, the rest of it all looks good to me! Thanks.

**Review by maxstarkenburg — APPROVED** [review]

**Review by maxstarkenburg — CHANGES_REQUESTED** [review]
Sorry, I think I approved too soon. I didn't look at the dblog till now, and noticed that I'm seeing a slew of notices whenever visiting content of any type. I'm seeing lots of:

Notice: Undefined index: #item in lai_preprocess_field() (line 95 of /home/academiccommons/www/html/themes/lai/lai.theme)
and
Notice: Undefined index: label in lai_preprocess_field() (line 94 of /home/academiccommons/www/html/themes/lai/lai.theme)

**Review by maxstarkenburg — APPROVED** [review]

**Review by maxstarkenburg — DISMISSED** [review]
Thanks. Applied to gwdev-maxs:446 and no more such error messages.

**Comment by maxstarkenburg** [comment]
@retrospec, sorry, had last-minute thoughts on this change, so see my last commit and commit message. 

(I tried to add you as a reviewer, but you didn't show up in the list, so I thought it was maybe because you were an assignee (hence unassigning you), but apparently it must be that one can't be a reviewer if one was the original pull-requester.)

**Comment by retrospec** [comment]
Looked over code changes on local dev yesterday afternoon. Looks good. 

We discussed possibly adjusting HTML across templates+ to use heading tags vs. just label classes for noted areas to address accessibility+ reasons. Should another ticket be created for that? Would that be rolled out post this release round?

**Comment by maxstarkenburg** [comment]
Thanks. Yeah, I think that would be best for now. I'll go ahead and make the new ticket.

**Pull request merged**
